apiVersion: v1
kind: Service
metadata:
  name: express-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: express-nginx
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007